package pt.isel.gape.transversal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.List;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import org.junit.jupiter.api.parallel.ResourceLock;

import pt.isel.gape.access.model.AccessProfileType;
import pt.isel.gape.common.config.ConnectionProvider;
import pt.isel.gape.transversal.model.Message;
import pt.isel.gape.transversal.model.MessageCreateCommand;
import pt.isel.gape.transversal.model.MessagePriority;
import pt.isel.gape.transversal.model.MessageReceipt;
import pt.isel.gape.transversal.model.MessageReceiptState;
import pt.isel.gape.transversal.model.MessageState;
import pt.isel.gape.transversal.model.MessageType;
import pt.isel.gape.transversal.service.MessageService;

@Execution(ExecutionMode.SAME_THREAD)
@ResourceLock("gape-db")
class MessageServiceTest {

    private static final Clock FIXED_CLOCK = Clock.fixed(Instant.parse("2026-02-04T17:00:00Z"), ZoneOffset.UTC);
    private static final String IP = "127.0.0.1";

    private ConnectionProvider connectionProvider;
    private MessageService messageService;

    @BeforeAll
    static void initializeDatabase() throws Exception {
        DatabaseTestSupport.resetDatabaseWithBaseSeed();
    }

    @BeforeEach
    void setUp() throws SQLException {
        DatabaseTestSupport.beginTestTransaction();
        connectionProvider = DatabaseTestSupport::openConnection;
        messageService = new MessageService(connectionProvider, FIXED_CLOCK);
    }

    @AfterEach
    void tearDown() throws SQLException {
        DatabaseTestSupport.rollbackTestTransaction();
    }

    @Test
    void participantSendsMessageToChannelRecipient() throws Exception {
        Message message = messageService.sendMessage(
                3L,
                null,
                AccessProfileType.TEACHER,
                textMessage(190L, 3L, List.of(4L)),
                IP
        );

        assertEquals(MessageState.SENT, message.state());
        assertEquals(3L, message.senderUserId());
        assertEquals(MessageReceiptState.DELIVERED, receiptState(4L, message.id()));
    }

    @Test
    void systemGeneratedMessageCanHaveNoSender() {
        Message message = messageService.sendSystemMessage(
                null,
                null,
                null,
                new MessageCreateCommand(
                        190L,
                        null,
                        null,
                        null,
                        "System Notice",
                        "Generated by system",
                        MessageType.SYSTEM,
                        MessagePriority.NORMAL,
                        null,
                        null,
                        List.of(4L)
                ),
                IP
        );

        assertNull(message.senderUserId());
        assertEquals(MessageState.SENT, message.state());
    }

    @Test
    void nonParticipantCannotSendMessage() {
        assertThrows(SecurityException.class, () -> messageService.sendMessage(
                1L,
                100L,
                AccessProfileType.ADMINISTRATOR,
                textMessage(190L, 1L, List.of(4L)),
                IP
        ));
    }

    @Test
    void actorCannotSpoofAnotherSender() {
        assertThrows(SecurityException.class, () -> messageService.sendMessage(
                4L,
                null,
                AccessProfileType.STUDENT,
                textMessage(190L, 3L, List.of(4L)),
                IP
        ));
    }

    @Test
    void replyOutsideChannelIsRejected() {
        assertThrows(IllegalArgumentException.class, () -> messageService.sendMessage(
                3L,
                null,
                AccessProfileType.TEACHER,
                new MessageCreateCommand(
                        191L,
                        3L,
                        222L,
                        null,
                        "Wrong channel reply",
                        "Invalid reply",
                        MessageType.TEXT,
                        MessagePriority.NORMAL,
                        null,
                        null,
                        List.of(3L)
                ),
                IP
        ));
    }

    @Test
    void userCannotReplyToOwnMessage() {
        assertThrows(IllegalArgumentException.class, () -> messageService.sendMessage(
                3L,
                null,
                AccessProfileType.TEACHER,
                new MessageCreateCommand(
                        190L,
                        3L,
                        222L,
                        null,
                        "Self reply",
                        "Invalid self reply",
                        MessageType.TEXT,
                        MessagePriority.NORMAL,
                        null,
                        null,
                        List.of(4L)
                ),
                IP
        ));
    }

    @Test
    void futureScheduledMessageIsNotDeliveredUntilProcessingDate() throws Exception {
        LocalDateTime scheduledAt = LocalDateTime.of(2026, 2, 4, 18, 0);
        Message message = messageService.sendMessage(
                3L,
                null,
                AccessProfileType.TEACHER,
                new MessageCreateCommand(
                        190L,
                        3L,
                        null,
                        null,
                        "Scheduled",
                        "Future message",
                        MessageType.TEXT,
                        MessagePriority.NORMAL,
                        null,
                        scheduledAt,
                        List.of(4L)
                ),
                IP
        );

        assertEquals(MessageState.SCHEDULED, message.state());
        assertNull(message.sentAt());
        assertEquals(MessageReceiptState.PENDING, receiptState(4L, message.id()));
        assertNull(receiptDeliveredAt(4L, message.id()));
        assertEquals(0, messageService.processScheduledMessages(IP));

        MessageService dueService = new MessageService(
                connectionProvider,
                Clock.fixed(Instant.parse("2026-02-04T18:00:01Z"), ZoneOffset.UTC)
        );

        assertEquals(1, dueService.processScheduledMessages(IP));
        assertEquals("sent", messageState(message.id()));
        assertEquals(MessageReceiptState.DELIVERED, receiptState(4L, message.id()));
    }

    @Test
    void attachmentMessageRequiresAttachment() {
        assertThrows(IllegalArgumentException.class, () -> messageService.sendMessage(
                3L,
                null,
                AccessProfileType.TEACHER,
                new MessageCreateCommand(
                        190L,
                        3L,
                        null,
                        null,
                        "Attachment",
                        "Missing attachment",
                        MessageType.ATTACHMENT,
                        MessagePriority.NORMAL,
                        null,
                        null,
                        List.of(4L)
                ),
                IP
        ));
    }

    @Test
    void readDateCannotPrecedeDeliveryDate() {
        LocalDateTime scheduledAt = LocalDateTime.of(2026, 2, 4, 18, 0);
        Message message = messageService.sendMessage(
                3L,
                null,
                AccessProfileType.TEACHER,
                new MessageCreateCommand(
                        190L,
                        3L,
                        null,
                        null,
                        "Scheduled read",
                        "Future delivery",
                        MessageType.TEXT,
                        MessagePriority.NORMAL,
                        null,
                        scheduledAt,
                        List.of(4L)
                ),
                IP
        );

        assertThrows(IllegalArgumentException.class, () -> messageService.markRead(
                4L,
                null,
                message.id(),
                LocalDateTime.of(2026, 2, 4, 17, 30),
                IP
        ));
    }

    @Test
    void marksDirectConversationReadInBulk() throws Exception {
        createDirectConversationWithUnreadMessages();

        int markedRead = messageService.markDirectConversationRead(
                4L,
                null,
                3L,
                LocalDateTime.of(2026, 2, 4, 18, 30),
                IP
        );

        assertEquals(2, markedRead);
        assertEquals(MessageReceiptState.READ, receiptState(4L, 9301L));
        assertEquals(MessageReceiptState.READ, receiptState(4L, 9302L));
        assertEquals(MessageReceiptState.DELIVERED, receiptState(3L, 9303L));
    }

    @Test
    void scheduleEventMessageUsesEventRecipientsAndContext() throws Exception {
        long channelId = createScheduleChannel();

        Message message = messageService.sendSystemMessage(
                null,
                null,
                null,
                new MessageCreateCommand(
                        channelId,
                        null,
                        null,
                        140L,
                        "Lesson reminder",
                        "Reminder generated from schedule",
                        MessageType.REMINDER,
                        MessagePriority.HIGH,
                        null,
                        LocalDateTime.of(2026, 2, 5, 17, 30),
                        List.of()
                ),
                IP
        );

        assertEquals(MessageState.SCHEDULED, message.state());
        assertEquals(MessageReceiptState.PENDING, receiptState(3L, message.id()));
        assertEquals(MessageReceiptState.PENDING, receiptState(4L, message.id()));
    }

    private static MessageCreateCommand textMessage(long channelId, long senderUserId, List<Long> recipients) {
        return new MessageCreateCommand(
                channelId,
                senderUserId,
                null,
                null,
                "Message",
                "Message body",
                MessageType.TEXT,
                MessagePriority.NORMAL,
                null,
                null,
                recipients
        );
    }

    private static MessageReceiptState receiptState(long userId, long messageId) throws SQLException {
        try (Connection connection = DatabaseTestSupport.openConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     SELECT state
                     FROM receive_message
                     WHERE id_user = ?
                       AND id_message = ?
                     """)) {
            statement.setLong(1, userId);
            statement.setLong(2, messageId);
            try (ResultSet resultSet = statement.executeQuery()) {
                assertTrue(resultSet.next());
                return MessageReceiptState.fromDatabaseValue(resultSet.getString("state"));
            }
        }
    }

    private static LocalDateTime receiptDeliveredAt(long userId, long messageId) throws SQLException {
        try (Connection connection = DatabaseTestSupport.openConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     SELECT delivered_at
                     FROM receive_message
                     WHERE id_user = ?
                       AND id_message = ?
                     """)) {
            statement.setLong(1, userId);
            statement.setLong(2, messageId);
            try (ResultSet resultSet = statement.executeQuery()) {
                assertTrue(resultSet.next());
                return resultSet.getTimestamp("delivered_at") == null
                        ? null
                        : resultSet.getTimestamp("delivered_at").toLocalDateTime();
            }
        }
    }

    private static String messageState(long messageId) throws SQLException {
        try (Connection connection = DatabaseTestSupport.openConnection();
             PreparedStatement statement = connection.prepareStatement("""
                     SELECT state
                     FROM message
                     WHERE id_message = ?
                     """)) {
            statement.setLong(1, messageId);
            try (ResultSet resultSet = statement.executeQuery()) {
                assertTrue(resultSet.next());
                return resultSet.getString("state");
            }
        }
    }

    private static long createScheduleChannel() throws SQLException {
        try (Connection connection = DatabaseTestSupport.openConnection();
             PreparedStatement channel = connection.prepareStatement("""
                     INSERT INTO channel (title, type, visibility, created_at, state)
                     VALUES ('Schedule Channel', 'system', 'participants', '2026-02-04 17:00:00', 'active')
                     """, java.sql.Statement.RETURN_GENERATED_KEYS)) {
            channel.executeUpdate();
            try (ResultSet generatedKeys = channel.getGeneratedKeys()) {
                generatedKeys.next();
                long channelId = generatedKeys.getLong(1);
                insertPair(connection, "associate_channel_class_group", "id_channel", "id_class_group", channelId, 50L);
                insertParticipation(connection, channelId, 3L, "teacher");
                insertParticipation(connection, channelId, 4L, "student");
                return channelId;
            }
        }
    }

    private static void createDirectConversationWithUnreadMessages() throws SQLException {
        try (Connection connection = DatabaseTestSupport.openConnection();
             PreparedStatement channelStatement = connection.prepareStatement("""
                     INSERT INTO channel (
                         id_channel, title, type, visibility, created_at, state
                     ) VALUES (
                         930, 'Unread direct message', 'message', 'participants', '2026-02-04 18:00:00', 'active'
                     )
                     """);
             PreparedStatement participationStatement = connection.prepareStatement("""
                     INSERT INTO participate_channel (
                         id_user, id_channel, role, joined_at, muted, state
                     ) VALUES
                         (3, 930, 'owner', '2026-02-04 18:00:00', 0, 'active'),
                         (4, 930, 'member', '2026-02-04 18:00:00', 0, 'active')
                     """);
             PreparedStatement messageStatement = connection.prepareStatement("""
                     INSERT INTO message (
                         id_message, id_channel, id_user_sender, id_parent_message, id_schedule_event_origin,
                         title, body, type, priority, attachment, created_at, updated_at, scheduled_at, sent_at, state
                     ) VALUES
                         (9301, 930, 3, NULL, NULL, 'First', 'First unread message.', 'text',
                          'normal', NULL, '2026-02-04 18:01:00', NULL, NULL, '2026-02-04 18:01:10', 'sent'),
                         (9302, 930, 3, NULL, NULL, 'Attachment', 'Attachment unread message.', 'attachment',
                          'normal', 'contents/pdf/unassigned/unread.pdf', '2026-02-04 18:02:00', NULL, NULL, '2026-02-04 18:02:10', 'sent'),
                         (9303, 930, 4, NULL, NULL, 'Sent', 'Message from current user.', 'text',
                          'normal', NULL, '2026-02-04 18:03:00', NULL, NULL, '2026-02-04 18:03:10', 'sent')
                     """);
             PreparedStatement receiptStatement = connection.prepareStatement("""
                     INSERT INTO receive_message (
                         id_user, id_message, delivered_at, read_at, state
                     ) VALUES
                         (4, 9301, '2026-02-04 18:01:20', NULL, 'delivered'),
                         (4, 9302, '2026-02-04 18:02:20', NULL, 'delivered'),
                         (3, 9303, '2026-02-04 18:03:20', NULL, 'delivered')
                     """)) {
            channelStatement.executeUpdate();
            participationStatement.executeUpdate();
            messageStatement.executeUpdate();
            receiptStatement.executeUpdate();
        }
    }

    private static void insertPair(
            Connection connection,
            String table,
            String firstColumn,
            String secondColumn,
            long first,
            long second
    ) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                INSERT INTO %s (%s, %s)
                VALUES (?, ?)
                """.formatted(table, firstColumn, secondColumn))) {
            statement.setLong(1, first);
            statement.setLong(2, second);
            statement.executeUpdate();
        }
    }

    private static void insertParticipation(Connection connection, long channelId, long userId, String role)
            throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("""
                INSERT INTO participate_channel (id_user, id_channel, role, joined_at, muted, state)
                VALUES (?, ?, ?, '2026-02-04 17:00:00', 0, 'active')
                """)) {
            statement.setLong(1, userId);
            statement.setLong(2, channelId);
            statement.setString(3, role);
            statement.executeUpdate();
        }
    }
}
